version: '3.3'
services:
  rst-workbench-frontend:
    labels:
      name: rst-workbench-frontend
      type: frontend
    build:
      context: .
      args:
      - DOMAIN
      dockerfile: Dockerfile-frontend-server
    environment:
    - DOMAIN
    restart: unless-stopped
    volumes:
    - ./nginx-certbot/data/nginx:/etc/nginx/conf.d
    - ./nginx-certbot/data/certbot/conf:/etc/letsencrypt
    - ./nginx-certbot/data/certbot/www:/var/www/certbot
    ports:
    - 80:80
    - 443:443
    command: '/bin/sh -c ''chown -R nginx:root /etc/letsencrypt && echo DOMAIN: $DOMAIN
      && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon
      off;"'''
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
    - ./nginx-certbot/data/certbot/conf:/etc/letsencrypt
    - ./nginx-certbot/data/certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h &
      wait $${!}; done;'
  corenlp:
    labels:
      name: corenlp
      type: constituency-parser
    image: nlpbox/corenlp:2021-04-18
    environment:
    - JAVA_XMX=4g
    ports:
    - 9000:9000
  codra-service:
    labels:
      name: codra
      format: codra
      type: rst-parser
    image: nlpbox/codra-service:2019-05-16
    ports:
    - 9100:8000
  dplp-service:
    labels:
      name: dplp
      format: dplp
      type: rst-parser
    image: nlpbox/dplp-service:2021-04-16
    ports:
    - 9101:8000
    environment:
    - CORENLP_ENDPOINT=http://corenlp:9000
  hilda-service:
    labels:
      name: hilda
      format: hilda
      type: rst-parser
    image: hilda-service:2018-10-18
    ports:
    - 9102:8000
  heilman-sagae-service:
    labels:
      name: heilman-sagae-2015
      format: hs2015
      type: rst-parser
    image: nlpbox/heilman-sagae-2015-service:2019-05-12-2
    ports:
    - 9103:8000
  feng-hirst-service:
    labels:
      name: feng-hirst-2014
      format: hilda
      type: rst-parser
    image: nlpbox/feng-hirst-service:2019-01-04
    ports:
    - 9104:8000
  neuraleduseg-service:
    labels:
      name: neuraleduseg
      type: discourse-segmenter
    image: nlpbox/neuraleduseg-service:2021-02-09
    ports:
    - 9105:8000
    entrypoint: 'hug -f neuralseg/splitter_api.py

      '
  stagedp-service:
    labels:
      name: stagedp
      type: rst-parser
      format: stagedp
    image: nlpbox/stagedp-service:10
    environment:
    - CORENLP_ENDPOINT=http://corenlp:9000
    - NEURALSEG_ENDPOINT=http://neuraleduseg-service:8000
    ports:
    - 9106:8000
    entrypoint: 'hug -f src/stagedp/parser_api.py

      '
  rst-converter-service:
    labels:
      name: rst-converter-service
      type: format-converter
    image: nlpbox/rst-converter-service:2021-03-14
    ports:
    - 9150:5000
  rstweb-service:
    labels:
      name: rstweb
      type: rst-visualizer
    image: nlpbox/rstweb-service:2019-12-02
    ports:
    - 9151:8080
